DemoBCDS/Models/EFBCDS.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoBCDS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCDS_DemoEntities : DbContext
    {
        public BCDS_DemoEntities()
            : base("name=BCDS_DemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
    }
}

DemoBCDS/Models/EFBCDS.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Anwar Ahmed\source\repos\DemoBCDS\DemoBCDS\Models\EFBCDS.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

DemoBCDS/Models/EFBCDS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

DemoBCDS/Models/EmployeeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DemoBCDS.Models
{
    public class EmployeeModel
    {
        public string Id { get; set; }

        [Required(ErrorMessage ="Employee Name Required")]
        public string EmpName { get; set; }

        [Range(25,35 ,ErrorMessage ="Employee Age Should in between 25 to 35")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Input age must be in numeric")]
        [Required]
        public string EmpAge { get; set; }

        [RegularExpression("^[0-9]*$", ErrorMessage = "Input EmpPhone must be in numeric")]
        public string EmpPhone { get; set; }

        [Required]
        public string Password { get; set; }

        [Required]
        [Compare("Password", ErrorMessage ="Password and Confirm Password must be same")]
        public string ConfirmPassword { get; set; }
    }
}

DemoBCDS/Models/tblDepartment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoBCDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartment
    {
        public int Id { get; set; }
        public string DepartName { get; set; }
        public string DepartDescription { get; set; }
    }
}

DemoBCDS/Models/tblEmployee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoBCDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int Id { get; set; }
        public string EmpName { get; set; }
        public string EmpAge { get; set; }
        public string EmpPhone { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
    }
}

DemoBCDS/Controllers/AjaxCRUDController.cs
using DemoBCDS.DAL;
using DemoBCDS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoBCDS.Controllers
{
    public class AjaxCRUDController : Controller
    {
        DbContext db = new DbContext();
        // GET: AjaxCRUD
        public ActionResult Index()
        {
            return View();
        }


        //Json Methods
        public JsonResult EmpList()
        {            
            return Json(db.employeeList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult AddEmployee(EmployeeModel data)
        {
            db.addEmployee(data);
            return Json("success",JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdateEmployee(EmployeeModel data)
        {
            db.updateEmployee(data);
            return Json("Success",JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetByEmpId(int Id)
        {
            return Json(db.empFindById(Id),JsonRequestBehavior.AllowGet);
        }
        public JsonResult DeleteEmployee(int Id)
        {
            db.deleteEmployee(Id);
            return Json("success",JsonRequestBehavior.AllowGet);
        }
    }
}

DemoBCDS/Controllers/EmployeeController.cs
using DemoBCDS.DAL;
using DemoBCDS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoBCDS.Controllers
{
    public class EmployeeController : Controller
    {
        DbContext db = new DbContext();
        // GET: Employee
        public ActionResult Index()
        {            
            return View(db.employeeList());
        }

        [HttpGet]
        public ActionResult CreateEmployee()
        {            
            return View();
        }
        [HttpPost]
        public ActionResult CreateEmployee(EmployeeModel data)
        {
            db.addEmployee(data);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditEmployee(int id)
        {            
            return View(db.empFindById(id));
        }
        [HttpPost]
        public ActionResult EditEmployee(EmployeeModel data)
        {
            db.updateEmployee(data);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult DeleteEmployee(int id)
        {
            return View(db.empFindById(id));
        }
        [HttpPost]
        public ActionResult DeleteEmployee(EmployeeModel data)
        {
            db.deleteEmployee(Convert.ToInt32(data.Id));
            return RedirectToAction("Index");
        }

    }
}

DemoBCDS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoBCDS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DemoBCDS/Views/AjaxCRUD/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome to Ajax Controller</h2>

<div class="container">
    <h2>Employees Record</h2>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" onclick="clearTextBox();">Add New Employee</button><br /><br />
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                
                <th>
                    EmpName
                </th>
                <th>
                    EmpAge
                </th>
                <th>
                    EmpPhone
                </th>
                
                <th>
                    Action
                </th>
            </tr>
        </thead>
        <tbody class="tbody">
        </tbody>
    </table>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title" id="myModalLabel">Add Employee</h4>
            </div>
            <div class="modal-body">
                <form>
                    
                    <div class="form-group">
                        <label for="Name">Name</label>
                        <input type="text" class="form-control" id="Name" placeholder="Name" />
                    </div>
                    <div class="form-group">
                        <label for="Age">Age</label>
                        <input type="text" class="form-control" id="Age" placeholder="Age" />
                    </div>
                    <div class="form-group">
                        <label for="Phone">Phone</label>
                        <input type="text" class="form-control" id="Phone" placeholder="Phone" />
                    </div>
                   
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnAdd" onclick="return Add();">Add</button>
                <button type="button" class="btn btn-primary" id="btnUpdate" style="display:none;" onclick="Update();">Update</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>  

@section scripts{
    
    <script>

        $(document).ready(function () {
            loadData();

        });
        var EmployeeID;
        //Load Data function
        function loadData() {
            $.ajax({
                url: "/AjaxCRUD/EmpList",
                type: "GET",
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (result) {
                    var html = '';
                    $.each(result, function (key, item) {
                        debugger
                        html += '<tr>';
                        html += '<td>' + item.EmpName + '</td>';
                        html += '<td>' + item.EmpAge + '</td>';
                        html += '<td>' + item.EmpPhone + '</td>';
                        html += '<td><a href="#" onclick="return getbyID(' + item.Id + ')">Edit</a> | <a href="#" onclick="Delele(' + item.Id + ')">Delete</a></td>';
                        html += '</tr>';
                    });
                    $('.tbody').html(html);
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });
        }

        //Add Data Function   
        function Add() {
            var res = validate();
            if (res == false) {
                return false;
            }
            var empObj = {
                EmpName: $('#Name').val(),
                EmpAge: $('#Age').val(),
                EmpPhone: $('#Phone').val()
            };
            $.ajax({
                url: "/AjaxCRUD/AddEmployee",
                data: JSON.stringify(empObj),
                type: "POST",
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (result) {
                    loadData();
                    $('#myModal').modal('hide');
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });
        }  

        //Function for getting the Data Based upon Employee ID  
        function getbyID(EmpID) {
            EmployeeID = EmpID;
            $('#Name').css('border-color', 'lightgrey');
            $('#Age').css('border-color', 'lightgrey');
            $('#Phone').css('border-color', 'lightgrey');
            $.ajax({
                url: "/AjaxCRUD/GetByEmpId/" + EmpID,
                typr: "GET",
                contentType: "application/json;charset=UTF-8",
                dataType: "json",
                success: function (result) {
                    $('#Name').val(result.EmpName);
                    $('#Age').val(result.EmpAge);
                    $('#Phone').val(result.EmpPhone);

                    $('#myModal').modal('show');
                    $('#btnUpdate').show();
                    $('#btnAdd').hide();
                },
                error: function (errormessage) {
                    debugger
                    alert(errormessage.responseText);
                }
            });
            return false;
        }

        //function for updating employee's record  
        function Update() {
            var res = validate();
            if (res == false) {
                return false;
            }
            
            var empObj = {
                Id: EmployeeID,
                EmpName: $('#Name').val(),
                EmpAge: $('#Age').val(),
                EmpPhone: $('#Phone').val()
            };
            $.ajax({
                url: "/AjaxCRUD/UpdateEmployee",
                data: JSON.stringify(empObj),
                type: "POST",
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (result) {
                    loadData();
                    $('#myModal').modal('hide');
                    $('#Name').val("");
                    $('#Age').val("");
                    $('#Phone').val("");
                    
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });
        }

        //function for deleting employee's record  
        function Delele(ID) {
            var ans = confirm("Are you sure you want to delete this Record?");
            if (ans) {
                $.ajax({
                    url: "/AjaxCRUD/DeleteEmployee/" + ID,
                    type: "POST",
                    contentType: "application/json;charset=UTF-8",
                    dataType: "json",
                    success: function (result) {
                        loadData();
                    },
                    error: function (errormessage) {
                        alert(errormessage.responseText);
                    }
                });
            }
        }  






























        //Function for clearing the textboxes  
        function clearTextBox() {
            $('#Name').val("");
            $('#Age').val("");
            $('#Phone').val("");
            $('#btnUpdate').hide();
            $('#btnAdd').show();
            $('#Name').css('border-color', 'lightgrey');
            $('#Age').css('border-color', 'lightgrey');
            $('#Phone').css('border-color', 'lightgrey');
            
        }
        //Valdidation using jquery  
        function validate() {
            var isValid = true;
            if ($('#Name').val().trim() == "") {
                $('#Name').css('border-color', 'Red');
                isValid = false;
            }
            else {
                $('#Name').css('border-color', 'lightgrey');
            }
            if ($('#Age').val().trim() == "") {
                $('#Age').css('border-color', 'Red');
                isValid = false;
            }
            else {
                $('#Age').css('border-color', 'lightgrey');
            }
            if ($('#Phone').val().trim() == "") {
                $('#Phone').css('border-color', 'Red');
                isValid = false;
            }
            else {
                $('#Phone').css('border-color', 'lightgrey');
            }
            
            return isValid;
        }  



    </script>
    
    } 

DemoBCDS/Views/Employee/CreateEmployee.cshtml
@model DemoBCDS.Models.EmployeeModel

@{
    ViewBag.Title = "CreateEmployee";
}

<h2>Create Employee</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmpName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoBCDS/Views/Employee/DeleteEmployee.cshtml
@model DemoBCDS.Models.EmployeeModel

@{
    ViewBag.Title = "DeleteEmployee";
}

<h2>Delete Employee</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmpName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpAge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpAge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConfirmPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfirmPassword)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> <br />
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DemoBCDS/Views/Employee/EditEmployee.cshtml
@model DemoBCDS.Models.EmployeeModel

@{
    ViewBag.Title = "EditEmployee";
}

<h2>Edit Employee Record</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.EmpName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoBCDS/Views/Employee/Index.cshtml
@model IEnumerable<DemoBCDS.Models.EmployeeModel>

@{
    ViewBag.Title = "Index";
}

<h2>Employees List</h2>

<p>
    @Html.ActionLink("Create New", "CreateEmployee", null, new { @style = "text-transform:capitalize;", @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmpName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmpAge)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmpPhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConfirmPassword)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EmpName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmpAge)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmpPhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ConfirmPassword)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditEmployee", new {  id=item.Id  }) |
            @Html.ActionLink("Delete", "DeleteEmployee", new {  id=item.Id  })
        </td>
    </tr>
}

</table>

DemoBCDS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DemoBCDS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DemoBCDS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

DemoBCDS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("CRUD By MVC", "Index", "Employee")</li>
                    <li>@Html.ActionLink("CRUD By Ajax", "Index", "AjaxCRUD")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>